import React from 'react';

export default ({ input }) => (
  <select {...input}>
    <option value="">Select a category</option>
    <option value="-1">None</option>
    <option value="71">Academic</option>
    <option value="44">Accounting / Finance</option>
    <option value="393">Administration</option>
    <option value="402">Agriculture</option>
    <option value="361">Automotive/Aerospace</option>
    <option value="347">Aviation</option>
    <option value="73">Banking/Insurance</option>
    <option value="74">Big Data/Business Analysis</option>
    <option value="118">Call Centre</option>
    <option value="175">Carer</option>
    <option value="363">Catering</option>
    <option value="77">Charity &amp; Voluntary</option>
    <option value="78">Chefs</option>
    <option value="79">Childcare</option>
    <option value="510">Christmas Jobs</option>
    <option value="346">Cleaning</option>
    <option value="80">Construction/Engineering</option>
    <option value="374">Consulting</option>
    <option value="174">Courier</option>
    <option value="171">Customer Service</option>
    <option value="81">Digital &amp; Creative</option>
    <option value="375">Distribution</option>
    <option value="82">Drivers</option>
    <option value="512">Dublin City</option>
    <option value="377">Education</option>
    <option value="83">Education/Training</option>
    <option value="378">Electronics</option>
    <option value="84">Energy/Renewable Energy</option>
    <option value="170">Entertainment</option>
    <option value="86">Financial Services</option>
    <option value="87">Fitness &amp; Leisure</option>
    <option value="88">Franchise/Business Opportunity</option>
    <option value="89">Graduate</option>
    <option value="90">Hair and Beauty</option>
    <option value="91">Healthcare/Medical/Nursing</option>
    <option value="92">Hotels</option>
    <option value="93">HR/Recruitment</option>
    <option value="94">IT</option>
    <option value="95">Legal</option>
    <option value="96">Managers/Supervisors</option>
    <option value="97">Manufacturing/Engineering</option>
    <option value="98">Marketing/Market Research</option>
    <option value="385">Media</option>
    <option value="404">Military</option>
    <option value="99">Miscellaneous</option>
    <option value="100">Motors</option>
    <option value="101">Multi-Lingual</option>
    <option value="511">New</option>
    <option value="508">Noel Recruitment</option>
    <option value="176">Other</option>
    <option value="102">Pharmaceutical/Science/Agricultural</option>
    <option value="103">Promotions/Merchandising</option>
    <option value="104">Property/Facilities Management</option>
    <option value="105">Pubs, Bars &amp; Clubs</option>
    <option value="106">Restaurants/Catering</option>
    <option value="107">Retail</option>
    <option value="384">Sales</option>
    <option value="108">Sales – €35k+</option>
    <option value="109">Sales – Up to €35k</option>
    <option value="110">Sales &amp; Marketing</option>
    <option value="111">Secretarial/Admin/PA</option>
    <option value="112">Security</option>
    <option value="113">Senior Appointments</option>
    <option value="172">Social Work</option>
    <option value="514">Spooky</option>
    <option value="114">Telecoms/Tech Support</option>
    <option value="115">Trades/Operative/Manual</option>
    <option value="173">Transport</option>
    <option value="116">Travel/Tourism</option>
    <option value="117">Warehouse/Logistics/Shipping</option>
  </select>
)
;
